### ISSUE TITLE
System crash when compile (with fix)

### ISSUE THREAD

**Issue by esteban142536** [asledgehammer/PipeWrench-Template#92]
When i try to start the compiler using `npm run compile` it throws the following error

`PipeWrenchTemplate on  master [✘!?] is 📦 v1.0.0 via  v14.18.1 took 3s
❯ npm run compile

> pipewrench_mod_template@1.0.0 compile /home/{me}/proyects/PZGenerator/PipeWrenchTemplate
> tstl

Configuration: {
  modInfo: {
    name: 'My First Mod',
    poster: './poster.png',
    description: 'arf',
    id: '12312312',
    url: 'https://www.google.com,'
  },
  modelsDir: './src/models',
  texturesDir: './src/textures',
  soundDir: './src/sound',
  scriptsDir: './src/scripts'
}

/home/{me}/proyects/PZGenerator/PipeWrenchTemplate/node_modules/@asledgehammer/tstl-pipewrench/dist/index.js:43
        let toImport = fromImport.replaceAll('.', '/');`

I fix it by changing the tstl-pipewrench index, replacing the `replaceAll ` to `replace('/../g', '/')`
It uses a regex because sometimes Javascript doesn't add the replaceAll to some strings
this also happen in the line 79

**Comment by JabDoesThings** [comment]
Yeah.. I know this issue all too well. I'll take a look and see if I can fix this tonight. It's an easy one. 

Thanks for reporting it.

**Comment by esteban142536** [comment]
There's a error in the fix, you should use `.replace(/\./g,'/')`

**Comment by JabDoesThings** [comment]
@esteban142536 Let me know if this issue is resolved. (use `npm i` again)

**Comment by esteban142536** [comment]
Yes, its working again
